name: 🔄 Автоматическая синхронизация Workspace

on:
  workflow_dispatch:
    inputs:
      sync_type:
        description: 'Тип синхронизации'
        required: true
        default: 'full'
        type: choice
        options:
        - full
        - seo-only
        - force
      commit_message:
        description: 'Сообщение коммита'
        required: false
        default: '🔄 Автоматическая синхронизация workspace'
        type: string
  schedule:
    # Запускается каждый час для проверки изменений
    - cron: '0 * * * *'
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'README.md'
      - '.github/workflows/auto-sync-workspace.yml'

jobs:
  auto-sync:
    runs-on: ubuntu-latest
    name: 🔄 Автосинхронизация
    
    steps:
      - name: 📥 Загрузка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🔍 Проверка изменений
        id: check-changes
        run: |
          echo "🔍 Проверяю изменения в workspace..."
          
          # Проверяем последние изменения
          if git diff --name-only HEAD~1 HEAD | grep -E '\.(js|html|css|yml|toml|json|md)$'; then
            echo "✅ Изменения обнаружены"
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "ℹ️ Изменений не обнаружено"
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
          
          # Проверяем тип синхронизации
          echo "sync_type=${{ github.event.inputs.sync_type }}" >> $GITHUB_OUTPUT
          echo "commit_message=${{ github.event.inputs.commit_message }}" >> $GITHUB_OUTPUT
      
      - name: 📦 Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 📥 Установка зависимостей
        run: |
          echo "📦 Устанавливаю зависимости..."
          npm ci
          echo "✅ Зависимости установлены"
      
      - name: 🔍 Проверка структуры проекта
        run: |
          echo "🔍 Проверяю структуру проекта..."
          
          # Проверяем наличие ключевых файлов
          local missing_files=()
          
          if [ ! -f "netlify/functions/renderer.js" ]; then
            missing_files+=("netlify/functions/renderer.js")
          fi
          
          if [ ! -f "netlify.toml" ]; then
            missing_files+=("netlify.toml")
          fi
          
          if [ ! -f "package.json" ]; then
            missing_files+=("package.json")
          fi
          
          if [ ! -f ".github/workflows/auto-deploy-seo.yml" ]; then
            missing_files+=(".github/workflows/auto-deploy-seo.yml")
          fi
          
          if [ ! -f ".github/workflows/quick-seo-update.yml" ]; then
            missing_files+=(".github/workflows/quick-seo-update.yml")
          fi
          
          if [ ${#missing_files[@]} -eq 0 ]; then
            echo "✅ Все файлы на месте"
          else
            echo "⚠️ Отсутствуют файлы:"
            for file in "${missing_files[@]}"; do
              echo "  - $file"
            done
          fi
      
      - name: 🔄 Автоматическая синхронизация
        if: steps.check-changes.outputs.has_changes == 'true' || github.event.inputs.sync_type == 'force'
        run: |
          echo "🔄 Выполняю автоматическую синхронизацию..."
          
          # Настраиваем Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Добавляем все изменения
          git add .
          
          # Создаем коммит
          COMMIT_MSG="${{ github.event.inputs.commit_message }}"
          if [ -z "$COMMIT_MSG" ]; then
            COMMIT_MSG="🔄 Автоматическая синхронизация workspace - $(date)"
          fi
          
          git commit -m "$COMMIT_MSG" || {
            echo "ℹ️ Нет изменений для коммита"
            exit 0
          }
          
          echo "✅ Коммит создан: $COMMIT_MSG"
      
      - name: 🚀 Отправка изменений
        if: steps.check-changes.outputs.has_changes == 'true' || github.event.inputs.sync_type == 'force'
        run: |
          echo "🚀 Отправляю изменения в GitHub..."
          
          # Проверяем, есть ли изменения для отправки
          if git log --oneline -1 | grep -q "🔄"; then
            git push origin main
            echo "✅ Изменения отправлены в GitHub"
          else
            echo "ℹ️ Нет изменений для отправки"
          fi
      
      - name: 🔍 Проверка результата
        run: |
          echo "🔍 Проверяю результат синхронизации..."
          
          # Показываем последние коммиты
          echo "📝 Последние коммиты:"
          git log --oneline -5
          
          # Показываем статус
          echo ""
          echo "📊 Статус репозитория:"
          git status --porcelain
          
          echo "✅ Проверка завершена"
      
      - name: 📱 Уведомление о завершении
        if: steps.check-changes.outputs.has_changes == 'true' || github.event.inputs.sync_type == 'force'
        run: |
          echo "🎉 АВТОСИНХРОНИЗАЦИЯ ЗАВЕРШЕНА!"
          echo "=================================="
          echo "✅ Статус: Успешно"
          echo "⏰ Время: $(date)"
          echo "🔄 Тип: ${{ github.event.inputs.sync_type }}"
          echo "💬 Сообщение: ${{ github.event.inputs.commit_message }}"
          echo "🌐 Изменения отправлены в GitHub"
          echo "📱 Сайт обновится автоматически"
      
      - name: ℹ️ Информация о пропуске
        if: steps.check-changes.outputs.has_changes == 'false' && github.event.inputs.sync_type != 'force'
        run: |
          echo "ℹ️ СИНХРОНИЗАЦИЯ ПРОПУЩЕНА"
          echo "============================"
          echo "💡 Причина: Изменений не обнаружено"
          echo "💡 Для принудительной синхронизации используйте 'force'"
          echo "💡 Или внесите изменения в файлы проекта"