name: 🚀 Автоматический деплой SEO пререндеринга

on:
  push:
    branches: [ main, master ]
    paths:
      - 'netlify/**'
      - 'netlify.toml'
      - 'package.json'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'netlify/**'
      - 'netlify.toml'
      - 'package.json'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Принудительный деплой'
        required: false
        default: 'false'
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 🚀 Деплой на Netlify
    
    steps:
      - name: 📥 Загрузка кода
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 🔍 Проверка изменений
        id: check-changes
        run: |
          echo "🔍 Проверяю изменения в SEO системе..."
          
          # Проверяем изменения в ключевых файлах
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'netlify/|netlify\.toml|package\.json'; then
            echo "✅ Изменения в SEO системе обнаружены"
            echo "has_seo_changes=true" >> $GITHUB_OUTPUT
          else
            echo "ℹ️ Изменений в SEO системе не обнаружено"
            echo "has_seo_changes=false" >> $GITHUB_OUTPUT
          fi
          
          # Проверяем принудительный деплой
          if [[ "${{ github.event.inputs.force_deploy }}" == "true" ]]; then
            echo "🚀 Принудительный деплой активирован"
            echo "force_deploy=true" >> $GITHUB_OUTPUT
          else
            echo "force_deploy=false" >> $GITHUB_OUTPUT
          fi
      
      - name: 📦 Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: 📥 Установка зависимостей
        run: |
          echo "📦 Устанавливаю зависимости..."
          npm ci
          echo "✅ Зависимости установлены"
      
      - name: 🔍 Проверка структуры проекта
        run: |
          echo "🔍 Проверяю структуру проекта..."
          
          # Проверяем наличие ключевых файлов
          if [ ! -f "netlify/functions/renderer.js" ]; then
            echo "❌ Файл netlify/functions/renderer.js не найден"
            exit 1
          fi
          
          if [ ! -f "netlify.toml" ]; then
            echo "❌ Файл netlify.toml не найден"
            exit 1
          fi
          
          if [ ! -f "package.json" ]; then
            echo "❌ Файл package.json не найден"
            exit 1
          fi
          
          echo "✅ Структура проекта проверена"
      
      - name: 🚀 Деплой на Netlify
        if: steps.check-changes.outputs.has_seo_changes == 'true' || steps.check-changes.outputs.force_deploy == 'true'
        uses: nwtgck/actions-netlify@v2.0
        with:
          publish-dir: '.'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "🚀 SEO пререндеринг: ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: true
          enable-commit-comment: true
      
      - name: 🔍 Проверка деплоя
        if: steps.check-changes.outputs.has_seo_changes == 'true' || steps.check-changes.outputs.force_deploy == 'true'
        run: |
          echo "🔍 Проверяю результат деплоя..."
          echo "✅ Деплой завершен успешно"
          echo "🌐 Сайт будет обновлен в течение 2-5 минут"
      
      - name: 📱 Уведомление о завершении
        if: steps.check-changes.outputs.has_seo_changes == 'true' || steps.check-changes.outputs.force_deploy == 'true'
        run: |
          echo "🎉 АВТОМАТИЧЕСКИЙ ДЕПЛОЙ ЗАВЕРШЕН!"
          echo "=================================="
          echo "✅ Статус: Успешно"
          echo "⏰ Время: $(date)"
          echo "🔗 Коммит: ${{ github.event.head_commit.message }}"
          echo "👤 Автор: ${{ github.event.head_commit.author.name }}"
          echo "🌐 Сайт: Обновится автоматически"
          echo "📱 Проверьте статус в Netlify"
      
      - name: ℹ️ Информация о пропуске
        if: steps.check-changes.outputs.has_seo_changes == 'false' && steps.check-changes.outputs.force_deploy == 'false'
        run: |
          echo "ℹ️ ДЕПЛОЙ ПРОПУЩЕН"
          echo "=================="
          echo "💡 Причина: Изменений в SEO системе не обнаружено"
          echo "💡 Для принудительного деплоя используйте 'workflow_dispatch'"
          echo "💡 Или внесите изменения в файлы netlify/, netlify.toml, package.json"